
mybatis:
    # config-locations: classpath:mybatis/mybatis-config.xml
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.atecher.mintools.model
    type-handlers-package: com.atecher.mintools.mapper


spring:
  profiles:
    active: prod
    datasource:
        name: mintools
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url:  jdbc:mysql://182.254.212.213:3306/mintools?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
        username: atecher
        password: hhw840129
        filters: stat,wall
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    thymeleaf:
       cache: false
       prefix: classpath:/templates/
       suffix: .html
       encoding: UTF-8
       content-type: text/html
       mode: HTML5


---

#开发环境
spring:
    profiles: dev
    datasource:
      url: jdbc:mysql://182.254.212.213:3306/mintools?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false

---

#生产环境
spring:
    profiles: prod
    datasource:
      url: jdbc:mysql://127.0.0.1:3306/mintools?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false


